server:
  port: 8082
databases:
  - user: admin
    password: admin
    host: localhost
    dbName: shopDev
  - user: order
    password: order
    host: localhost
    dbName: order
security:
  jwt: 
    key: dfkjughileruy9812347uy
