server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: 33306
  username: root
  password: root1234
  daname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

databases:
  - user: admin
    password: admin
    host: localhost
    dbName: shopDev
  - user: order
    password: order
    host: localhost
    dbName: order
security:
  jwt: 
    key: dfkjughileruy9812347uy
